ColorlibHQ/gentelella

- production/index.html
Would be nice to reach inbox in the notification area also (on See all alerts).
> Inbox click

- nbproject/private/private.xml
- production/css/custom.css
- production/js/custom.js
I have Found that, right_col have max-height fixed,I have made it responsive as per the screen height.
> right_col height set to screen height

- README.md
- documentation/index_cn.html
Hi,I add the Chinese document to it.
> Add Chinese document

- production/js/flot/jquery.flot.orderBars.js
updates/fixes to flot-orderBars from [emmerich/flot-orderBars](https://github.com/emmerich/flot-orderBars)
> update/fix flot-orderBars

- production/empty.html
I added an empty.html file, it's the index.html where all content have been removed.
> emtpy html

- production/form_validation.html
Add telephone number field to avoid confusion to number field validation 
Issues: https://github.com/puikinsh/gentelella/issues/58
> Add telephone number validation

- production/page_404.html
> Fix minor spelling issue on 404 page

- .gitignore
- nbproject/private/private.xml
- nbproject/project.properties
- nbproject/project.xml
Another option is ignore this folder globally using `~/.gitignore_global`.
> Ignore folder nbproject

- production/css/custom.css
- production/e_commerce.html
- production/echarts.html
- production/icons.html
- production/inbox.html
- production/index2.html
- production/js/custom.js
- production/other_charts.html
- production/profile.html
- production/project_detail.html
- production/tables_dynamic.html
- production/typography.html
- Fix menu not opening in new tab when holding ctr+tab
- Fix some panel toolbox not functional
> Fix menu and panel toolbox

- production/css/custom.css
- production/form.html
- production/inbox.html
- production/js/custom.js
- production/less/custom.css
- Change button layout
- Add compose
> Enhance inbox page

- package.json
@christianesperar I've added the package.json file, but I assume someone on your side will want to [publish it](https://docs.npmjs.com/cli/publish).
Fixes https://github.com/puikinsh/gentelella/issues/131
> Add package.json file for npm package

- bower.json
- changelog.md
- package.json
Please don't merge until npm is publish
> Package release update

- README.md
Hello! Thanks for this template!
I made an extension for yii2. Could you add it to your readme?
> Extension for yii2 based on Gentelella

- package.json
Added _main_ attribute to make compatible with **brunch** build tool
> added main attribute to package.json

- production/form_buttons.html
> Fix dropdown

- production/form.html
> Remove conflicts on merge #375

- README.md
Add PHP / Laravel 5 boilerplate project with Gentelella Admin theme support
> Add Laravel Gentelella support

- README.md
Modified Gentelella to work with Django
> Gentelella for Django

- production/form.html
> inline form is not working

- README.md
add Flask support for gentelella + fix small typo
> add Flask support for gentelella + fix small typo

- src/scss/custom.scss
Fixing the issue described here:
https://github.com/puikinsh/gentelella/issues/608
> fix unrecognised input when requiring css in angular JS

- build/js/custom.js
Solution for this problem: https://github.com/puikinsh/gentelella/issues/503
> Sample PNotify message is not a part of release

- README.md
Add Gentelella RTL version in Gentelella for other platform or framework section
> Add Gentelella RTL version

- production/icons.html
- src/scss/custom.scss
Reverts puikinsh/gentelella#652
> Revert "Fix Spinner Icons in spin when add .fa-spin class in Icons.html"

- README.md
I create an extension on Yii2 inspired from [Gentelella on Yii framework 2](https://github.com/yiister/yii2-gentelella)
> add Gentelella-rtl on Yii2

- production/general_elements.html
#822 Solved !! 
Hey Developers! 
I have tried to touch it as little as Possible!!
> Fixed Modal Title on Left

- production/form.html
#896  The _`input types`_ have been changed from _` text`_ type to _`date`_ and _`email`_ at required places.
**In Document:** _gentelella/production/form.html_
- The _Date Of Birth_ Input Was Accepting Text Types (Which was wrong).
- The Inputs of data types have been changed to their correct types.
- The Input field is initially `text type` and changes to` date type` on `onclick `, `onfocus` and `onmouseover` events.
- Created A function to change the `input field type` back to text, _60 seconds after_ `onmouseout` and `onblur` events (As the user may need about 60 seconds to scroll and select the date using the _browser inbuilt calendar_ ).
The line numbers may vary a bit
- - Line 418: Changed `input type` from `_text_` to `_email_`.
- - Line 423: Changed `input type` from `_text_` to …
> Changed Field Input Types At Required Places

- production/form_buttons.html
when I saw your webpage I found bugs in button size where the medium-size button is smaller than the small-size button. So I fixed that bug
> fixed bugs in form button sizes
